# Generated by Django 4.2.20 on 2025-03-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderitem_item_name_orderitem_order_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
