# Generated by Django 4.2.20 on 2025-03-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orderitem_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
