# Generated by Django 4.2.20 on 2025-04-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='file',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
